# Generated by Django 3.2.13 on 2022-04-29 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('imageA', models.ImageField(upload_to='')),
                ('imageB', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('countA', models.ManyToManyField(related_name='count_A', to=settings.AUTH_USER_MODEL)),
                ('countB', models.ManyToManyField(related_name='count_B', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
